# Generated by Django 5.2.4 on 2025-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=200, verbose_name='Lastname')),
                ('user_name', models.CharField(max_length=200, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
