# Generated by Django 5.2.4 on 2025-07-15 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
